package com.kmedtech.my_springboot_app.service;

import com.kmedtech.my_springboot_app.dto.StudentDTO;
import com.kmedtech.my_springboot_app.dto.StudentMapper;
import com.kmedtech.my_springboot_app.model.Student;
import com.kmedtech.my_springboot_app.repository.StudentRepository;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.util.List;

@Service
public class StudentService {

    private final StudentRepository studentRepository;

    // Constructor injection
    public StudentService(StudentRepository studentRepository) {
        this.studentRepository = studentRepository;
    }

    // Helper method to find the Student Entity internally
    private Student findStudentEntityById(Long id) {
        return studentRepository.findById(id)
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND, "Student not found with id: " + id));
    }

    // Retrieve all students as DTOs
    public List<StudentDTO> getAllStudents() {
        return studentRepository.findAll()
                .stream()
                .map(StudentMapper::toDTO)
                .toList();
    }

    // Retrieve a student by ID as DTO
    public StudentDTO getStudentById(Long id) {
        Student student = findStudentEntityById(id);
        return StudentMapper.toDTO(student);
    }

    // Create a new student from DTO and return DTO
    public StudentDTO createStudent(StudentDTO studentDTO) {
        if (studentRepository.findByEmail(studentDTO.getEmail()).isPresent()) {
            throw new ResponseStatusException(
                    HttpStatus.BAD_REQUEST, "Email already exists: " + studentDTO.getEmail());
        }
        
        Student student = StudentMapper.toEntity(studentDTO);
        student.setId(null); // Ensure ID is generated by database
        Student savedStudent = studentRepository.save(student);
        return StudentMapper.toDTO(savedStudent);
    }

    // Update an existing student using DTO and return DTO
    public StudentDTO updateStudent(Long id, StudentDTO studentDetailsDTO) {
        Student student = findStudentEntityById(id);

        if (!student.getEmail().equalsIgnoreCase(studentDetailsDTO.getEmail()) &&
                studentRepository.findByEmail(studentDetailsDTO.getEmail()).isPresent()) {
            throw new ResponseStatusException(
                    HttpStatus.BAD_REQUEST, "Email already exists: " + studentDetailsDTO.getEmail());
        }

        student.setFirstName(studentDetailsDTO.getFirstName());
        student.setLastName(studentDetailsDTO.getLastName());
        student.setEmail(studentDetailsDTO.getEmail());
        student.setAge(studentDetailsDTO.getAge());

        Student updatedStudent = studentRepository.save(student);
        return StudentMapper.toDTO(updatedStudent);
    }

    // Delete a student by ID
    public void deleteStudent(Long id) {
        Student student = findStudentEntityById(id);
        studentRepository.delete(student);
    }
}
